name: 检查并重新部署 Appwrite Site (CLI版)

on:
  schedule:
    - cron: '*/15 * * * *' # 每15分钟自动运行一次
  workflow_dispatch: # 允许手动触发

jobs:
  check-and-redeploy:
    runs-on: ubuntu-latest
    env:
      APPWRITE_PROJECT_ID: ${{ secrets.APPWRITE_PROJECT_ID }}
      APPWRITE_SITE_ID: ${{ secrets.APPWRITE_SITE_ID }}
      APPWRITE_API_ENDPOINT: ${{ secrets.APPWRITE_API_ENDPOINT || 'https://syd.cloud.appwrite.io/v1' }}
      APPWRITE_API_KEY: ${{ secrets.APPWRITE_API_KEY }}
      GIT_CFSUB_PAT: ${{ secrets.GIT_CFSUB_PAT }}

    steps:
      - name: 检查环境变量
        run: |
          if [ -z "$APPWRITE_PROJECT_ID" ]; then echo "::error::Secret 'APPWRITE_PROJECT_ID' 未设置！"; exit 1; fi
          if [ -z "$APPWRITE_SITE_ID" ]; then echo "::error::Secret 'APPWRITE_SITE_ID' 未设置！"; exit 1; fi
          if [ -z "$APPWRITE_API_KEY" ]; then echo "::error::Secret 'APPWRITE_API_KEY' 未设置！"; exit 1; fi
          if [ -z "$GIT_CFSUB_PAT" ]; then echo "::error::Secret 'GIT_CFSUB_PAT' 未设置！"; exit 1; fi
          echo "所有必要的 Secrets 都已加载。"

      - name: 安装 Appwrite CLI
        run: npm install -g appwrite-cli

      - name: Appwrite CLI 配置
        id: cli_setup
        run: |
          # 【最终修正】使用正确的 CLI 参数
          appwrite client --endpoint "${APPWRITE_API_ENDPOINT}"
          appwrite client --project-id "${APPWRITE_PROJECT_ID}"
          appwrite client --key "${APPWRITE_API_KEY}"
          echo "Appwrite CLI 配置成功！"

      - name: 获取部署状态
        id: get_status
        run: |
          echo "正在获取部署列表 (使用 CLI)..."
          DEPLOYMENTS_JSON=$(appwrite sites list-deployments --siteId "${APPWRITE_SITE_ID}" --json)
          
          FAILED_DEPLOYMENT_IDS=$(echo "$DEPLOYMENTS_JSON" | jq -r '.deployments[] | select(.status == "failed") | ."$id"')
          BUILDING_DEPLOYMENT_IDS=$(echo "$DEPLOYMENTS_JSON" | jq -r '.deployments[] | select(.status == "building") | ."$id"')
          TOTAL_DEPLOYMENTS=$(echo "$DEPLOYMENTS_JSON" | jq -r '.total')
          
          if [ -n "$FAILED_DEPLOYMENT_IDS" ] || [ "$TOTAL_DEPLOYMENTS" -eq 0 ]; then
            if [ "$TOTAL_DEPLOYMENTS" -eq 0 ]; then
              echo "没有发现任何部署，将触发首次部署。"
            else
              echo "发现一个或多个失败的部署。"
            fi
            FAILED_IDS_ONELINE=$(echo "$FAILED_DEPLOYMENT_IDS" | tr '\n' ' ')
            BUILDING_IDS_ONELINE=$(echo "$BUILDING_DEPLOYMENT_IDS" | tr '\n' ' ')
            echo "failed_ids=${FAILED_IDS_ONELINE}" >> $GITHUB_OUTPUT
            echo "building_ids=${BUILDING_IDS_ONELINE}" >> $GITHUB_OUTPUT
            echo "status=redeploy" >> $GITHUB_OUTPUT
          elif [ -n "$BUILDING_DEPLOYMENT_IDS" ]; then
            echo "正在部署中，ID(s)：${BUILDING_DEPLOYMENT_IDS}"
            echo "status=building" >> $GITHUB_OUTPUT
          else
            echo "没有发现失败或进行中的部署，状态正常。"
            echo "status=ok" >> $GITHUB_OUTPUT
          fi

      - name: 触发新部署并清理
        if: steps.get_status.outputs.status == 'redeploy'
        run: |
          # 1. 使用 Appwrite CLI 触发新的部署
          echo "正在触发一次新的部署 (使用 CLI)..."
          NEW_DEPLOYMENT_JSON=$(appwrite sites createDeployment --siteId "${APPWRITE_SITE_ID}" --activate --json --yes)
          
          echo "--- Appwrite CLI 响应 ---"
          echo "$NEW_DEPLOYMENT_JSON"
          echo "--------------------------"

          NEW_DEPLOYMENT_ID=$(echo "$NEW_DEPLOYMENT_JSON" | jq -r '."$id"')
          if [ -z "$NEW_DEPLOYMENT_ID" ] || [ "$NEW_DEPLOYMENT_ID" == "null" ]; then
            echo "::error::使用 CLI 触发新部署失败！请检查上面的响应以获取详细错误信息。"
            exit 1
          fi
          echo "已成功触发新部署，ID: ${NEW_DEPLOYMENT_ID}"

          # 2. 轮询获取日志
          echo "等待构建日志生成..."
          BASE64_NODE=""
          for i in {1..10}; do
            sleep 10
            echo "正在获取日志 (尝试次数: $i)..."
            LOGS_OUTPUT=$(curl -s --location --request GET "${APPWRITE_API_ENDPOINT}/sites/${APPWRITE_SITE_ID}/deployments/${NEW_DEPLOYMENT_ID}/builds/1/logs" \
            --header "X-Appwrite-Project: ${APPWRITE_PROJECT_ID}" \
            --header "X-Appwrite-Key: ${APPWRITE_API_KEY}")
            BASE64_NODE=$(echo "$LOGS_OUTPUT" | jq -r '.logs' | grep -oE '[A-Za-z0-9+/=]{200,}' | head -n 1)
            if [ -n "$BASE64_NODE" ]; then
              echo "已成功从日志中提取节点信息！"
              break
            fi
          done

          if [ -z "$BASE64_NODE" ]; then
            echo "::error::超时：在100秒内未能从日志中提取到节点信息。"
            exit 1
          fi

          # 3. 推送到另一个仓库
          echo "正在将节点信息推送到 CFSub 仓库..."
          echo "$BASE64_NODE" > appwrite_base64.txt
          git clone https://x-access-token:${GIT_CFSUB_PAT}@github.com/yutian81/CFSub.git
          mv appwrite_base64.txt CFSub/nodes/
          cd CFSub
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add nodes/appwrite_base64.txt
          if git diff --staged --quiet; then
            echo "节点信息无变化，无需推送。"
          else
            git commit -m "自动更新 Appwrite 节点信息"
            git push
            echo "已成功将新节点信息推送到 CFSub 仓库。"
          fi
          cd ..

          # 4. 使用 Appwrite CLI 清理旧部署
          echo "正在清理所有旧的部署 (使用 CLI)..."
          if [ -n "${{ steps.get_status.outputs.failed_ids }}" ]; then
            for FAILED_ID in ${{ steps.get_status.outputs.failed_ids }}; do
              echo "  - 正在删除失败的部署，ID: ${FAILED_ID}"
              appwrite sites deleteDeployment --siteId "${APPWRITE_SITE_ID}" --deploymentId "${FAILED_ID}" --yes
            done
          fi
          
          if [ -n "${{ steps.get_status.outputs.building_ids }}" ]; then
            for BUILDING_ID in ${{ steps.get_status.outputs.building_ids }}; do
              if [ "$BUILDING_ID" != "$NEW_DEPLOYMENT_ID" ]; then
                echo "  - 正在删除旧的进行中部署，ID: ${BUILDING_ID}"
                appwrite sites deleteDeployment --siteId "${APPWRITE_SITE_ID}" --deploymentId "${BUILDING_ID}" --yes
              else
                echo "  - 跳过删除新创建的部署，ID: ${BUILDING_ID}"
              fi
            done
          fi
          echo "已完成旧部署的清理。"
